### ISSUE TITLE
Conditions of use of LASSO and OAMP

### ISSUE THREAD

**Issue by xb1176989662** [STARainZ/CG-OAMP-NET#1]
The OAMP algorithm is based on the LASSO problem, but because of the existence of the 1 norm in LASSO, the solution is sparse, so if the signal itself is not sparse or not sparse through the Fourier transform to the frequency domain, can it still be used under such conditions

**Comment by STARainZ** [comment]
Hi Bin Xu,

The OAMP algorithm can also be derived from the message passing perspective/in the Bayes-optimal setting similar to the AMP algorithm.  The Bayes-optimal OAMP requires the prior of the signal to be known and applies to non-sparse signals (e.g., the commonly used QAM modulation signals in wireless communications). You can refer to [1] and [2] for details.

[1] J. Ma and L. Ping, “Orthogonal AMP,” IEEE Access, vol. 5, pp. 2020–2033, Jan. 2017.
[2] Q. Zou and H. Yang, “A concise tutorial on approximate message passing,” arXiv preprint arXiv:2201.07487, 2022.

Best regards,
Xingyu Zhou
